### ISSUE TITLE
Document Convention for Use of Getters with or without get

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1024]
### Description of the task
Some classes have getters prefixed by get, i.e. getName() and some don't, i.e. x(), y(), name(). 

### Acceptance criteria

- [ ] Document convention
- [ ] Refactor code to follow convention

**Comment by garethellis0** [comment]
I think that the advice should be to always prefix with `get`, in order to make functions consistent, with the exception being classes that are _super_ commonly used, like `Point`, where we can make the getter name just the name of what it's getting for brevity's sake. @MathewMacDougall @akhilveeraghanta @jonathanlew - thoughts?

**Comment by jonathanlew** [comment]
Have we scoped out what would change under that rule?

**Comment by jonathanlew** [comment]
#915 is related to this issue

**Comment by MathewMacDougall** [comment]
Ah wish I saw this before the meeting today we should have talked in person.

> I think that the advice should be to always prefix with get, in order to make functions consistent

This assumes that we are currently using `get` more often than not. Is that the case? Do we have an argument one way or the other that is not related to consistency?

Otherwise I agree about the classes that are really commonly used, but that's somewhat of an arbitrary cutoff. I don't think much would change under this rule because I think we currently use `get` for almost everything.

Which brings up another point, it seems we have chosen to use `get` even for boolean types sometimes, which are sometimes more commonly prefixed with `is`. Should we make a decision on that too here?

Overall I don't want to go too deep into this because it's not something I'm confident we can enforce, but we absolutely do want some level of consistency and sanity.

**Comment by garethellis0** [comment]
I like the general concept of  using `get` as a prefix in most cases, `is` for boolean functions, and no prefix for _super_ commonly used functions. Without adding `clang-tidy` support this is tricky to support, but at least defining what's correct saves people from having this debate in the future!

**Comment by garethellis0** [comment]
For anyone wondering, supporting clang-tidy is a ticket here: https://github.com/UBC-Thunderbots/Software/issues/839. If we think this is important enough I can prioritize it.

**Comment by MathewMacDougall** [comment]
Can clang-tidy enforce naming conventions like this?

**Comment by garethellis0** [comment]
Ah good point. Just checked and it doesn't look like it. Also this is a flexible requirement, so it would be pretty tricky to come up with a totally generic way of saying what is/is not valid.

**Comment by MathewMacDougall** [comment]
> I like the general concept of using get as a prefix in most cases, is for boolean functions, and no prefix for super commonly used functions

I'm fine with this then, since it's most similar to what we already have and what people are used to. The only main discrepancy I think would be the use of `is`, but we can just address that as we see it. The action item here should be to document this convention if everyone agrees?

**Comment by jonathanlew** [comment]
> I'm fine with this then, since it's most similar to what we already have and what people are used to. The only main discrepancy I think would be the use of `is`, but we can just address that as we see it. The action item here should be to document this convention if everyone agrees?

I'd just add that we have boolean-like values such as `BallCollisionType` enum and I think that using `get` for enums makes sense. To make our code _optimally_ readable (I'm not suggesting we should do this 😛 ), we'd have enum for every boolean and we could use get for all of them. But that's to say that if have a problematic boolean that uses `is`, then the solution is to make it an enum and use `get`

**Comment by garethellis0** [comment]
That's a good point. I had to think about this a bit, but I think the dividing line for when something should be an enum vs a boolean is when one of:
a) There are potentially more then two logical states (even if we just have two in our code).
b) There is not a clear "true" value from a high level perspective.

This is definitely all very fuzzy and should be judged on a per-case basis though.

**Comment by garethellis0** [comment]
I'm also not sure that replacing _all_ booleans with enums would make the code "optimally" readable :stuck_out_tongue:
