### ISSUE TITLE
Navigator Does Not Appear To Be Pathing Around The Ball Or Other Robots

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1057]
### Description of the task
robot's don't seem to be pathing around anything (ie. the ball, enemies, or each other).
Repro:
- run `bazel run //software:full_system -- --backend=grsim`
- set Play Override to Example Play and place the ball such that the robots must navigate around enemies to get to it
- friendly robots were then observed contacting both enemy robots and the ball

### Acceptance criteria

- [ ] Friendly robots avoid the ball
- [ ] Friendly robots avoid enemy robots
- [ ] Friendly robots avoid each other
### Blocked By
#1022 #1001

**Comment by jonathanlew** [comment]
This is likely caused by AI lag. When the AI doesn't update commands sent to grsim fast enough, grsim will show robots colliding even if the path planner is pathing around obstacles. I see obstacles being sent to the path planner. Question is if these are the right ones. I will leave further investigation to after #1022 and #1001
