### ISSUE TITLE
Refine usage of loop_forever in Actions

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#1267]
### Description of the task

Created from conversation in #1261 

Some Actions like `Kick` and `Chip` currently have the option to loop forever, which doesn't necessarily make sense. We should audit our current list of actions to determine what should expose the `loop_forever` parameter or not, and what the  default should be (if any).

In the case of `Kick` and `Chip`, we will need to implement something to detect the "done" condition like if the ball has been kicked or not.

### Acceptance criteria

- [ ] For all actions, determine if they should expose the `loop_forever` parameter. If they should not, determine what the default value should be
- [ ] Implement the above changes
- [ ] Implement any new "done" conditions that are necessary

**Comment by MathewMacDougall** [comment]
@garethellis0 @jonathanlew @amrm3lm

**Comment by MathewMacDougall** [comment]
Current status as of #1261 

| **Action**        | `loop_forever` exposed, default value           | Suggested change (`loop_forever` exposed, default value)  |
| ------------- |:-------------:| -----:|
| Chip      | No, default=`true` | No, default=`false` |
| Dribble      | No, default=`false`      |  No change |
| Intercept Ball | Yes      |  No, default=`false` |
| Kick | No, default=`true`      |  No, default=`false` |
| Move | Yes      |  No change? |
| MoveSpin | No, default=`false`      |  Yes (should probably be same as move) |
| Pivot | No, default=`true`      | No, default=`false` |
| Stop | Yes      | No? |

I'm sort of realizing that because Actions _generally_ don't represent the higher-level ideas of roles, there's very few uses / needs for `loop_forever` to be true or exposed.

Most Actions are very "finite" like kicking or intercepting. The most interesting cases IMO are Move, MoveSpin, Pivot, and Stop because they relate purely to movement.

When thinking about usages of `loop_forever`, the example I always give is the `ShadowEnemy` tactic. You want to be always moving and tracking the enemy, even if they stop for a while and you reach your destination.

The reason I'm unsure about the "movement related" actions is: If an Action reaches its done state (aka position), but then gets moved by an external factor, should it still try to return to its done state even if `loop_forever=false`? Currently, this would not be the case because of how coroutines work, hence the whole `restart` thing.

Should it be up to the tactic to constantly restart an action if it wants? Do we even care about getting moved by external forces since this is presumably uncommon? What about the case where we want to "hold our ground" against a pushing robot?

**Comment by amrm3lm** [comment]
very cool table

in further support for having chip/kick not loop forever, it seems that the shoot tactics already assume the kick action will be done at some point and depend on the action completing so that they themselves are done. Similarly shoot plays assume shoot tactcs will be done eventually. 

>The reason I'm unsure about the "movement related" actions is: If an Action reaches its done state (aka position), but then gets moved by an external factor, should it still try to return to its done state even if loop_forever=false? Currently, this would not be the case because of how coroutines work, hence the whole restart thing.

wouldnt the tactic that calls the action go to the next step in the tactic once the robot reaches the desired position, meaning that the move action wont be called again? 
I think this behavior could be created on the tactic level if needed

> Should it be up to the tactic to constantly restart an action if it wants? 

I think this is fair, and im guessing was the reason behind having the "loop_forever" param in the first place. especially if the cases where we want to constantly restart an action are limited (and probably only make sense to have in certain tactics).

Also if we're looking at specific done conditions should we consider making the done() method virtual/not have it depend on the coroutine? because otherwise there is a one "call" delay between  when an action is effectively done and when we actually say its done (ie when the coroutine finishes). For example the kick action yields the kickInent, but the coroutine is not done until its called again to drop out of the function.

**Comment by garethellis0** [comment]
> The reason I'm unsure about the "movement related" actions is: If an Action reaches its done state (aka position), but then gets moved by an external factor, should it still try to return to its done state even if loop_forever=false? Currently, this would not be the case because of how coroutines work, hence the whole restart thing.

IMO no, the concept of "done" in an action should just mean that the action completed what was asked of it, not that it's maintaining some time-invariant condition. From a technical perspective, this is simpler to maintain, and fits just fine with how almost all of our logic is setup (ie. "once action is done, do this other thing immediately")

> Should it be up to the tactic to constantly restart an action if it wants? Do we even care about getting moved by external forces since this is presumably uncommon? What about the case where we want to "hold our ground" against a pushing robot?

IMO something like a "Move" action should be done once it reaches it's goal. If we wanted a "shove" behaviour, that should be a separate action with it's own done condition IMO.

> wouldnt the tactic that calls the action go to the next step in the tactic once the robot reaches the desired position, meaning that the move action wont be called again?
I think this behavior could be created on the tactic level if needed

Hmm, it depends. If the tactic is waiting to get to the right position then yep, it will move on. It seems (at least to me) a bit more elegant to just be able to wait for the action to finish, then move on. This way the determination of "done" for an action is coupled to that action, instead of us having to re-implement the "done" condition in every tactic where that action is used. 

> Also if we're looking at specific done conditions should we consider making the done() method virtual/not have it depend on the coroutine? because otherwise there is a one "call" delay between when an action is effectively done and when we actually say its done (ie when the coroutine finishes). For example the kick action yields the kickInent, but the coroutine is not done until its called again to drop out of the function.

That's a great point! Overall I think the extra effort of maintaining `done` methods for each subclass is probably not quite worth the effort / potential for bugs, especially given how simple the current check is. Definitely a good trade-off to be explicit about making though!

**Comment by MathewMacDougall** [comment]
> Overall I think the extra effort of maintaining done methods for each subclass is probably not quite worth the effort / potential for bugs, especially given how simple the current check is.

This is how it worked many years ago, and indeed was difficult to maintain.

@garethellis0 seems like you're almost suggesting removing `loop_forever` from Actions entirely?

Yea it was really only things like shoving and maintaining some higher-level invariants I'm worried about. I do think it's reasonable to defer that to Tactics, just not entirely sure what it would look like in all cases.

**Comment by garethellis0** [comment]
Sorry, just to be clear, I think that `loop_forever` is fine, we just need to be selective about how we use it (see your table above). What made you think was suggesting we remove it entirely?

**Comment by MathewMacDougall** [comment]
> Hmm, it depends. If the tactic is waiting to get to the right position then yep, it will move on. It seems (at least to me) a bit more elegant to just be able to wait for the action to finish, then move on. This way the determination of "done" for an action is coupled to that action, instead of us having to re-implement the "done" condition in every tactic where that action is used.

Based on my table, the only Actions we would consider keeping `loop_forever` for are the "movement related ones", which you made sound like wasn't needed since generally the tactics wait for actions to finish then move on immediately.

We can start my making the changes in the table, unless anyone has suggestions for other changes. This is less work than removing `loop_forever` entirely to start. We can see how our use cases develop.

**Comment by garethellis0** [comment]
Fine by me, the suggested changes in the table seem entirely reasonable to me, at least for now.

**Comment by amrm3lm** [comment]
sounds good, i'll start making the changes mentioned in the table

**Comment by jonathanlew** [comment]
> IMO no, the concept of "done" in an action should just mean that the action completed what was asked of it, not that it's maintaining some time-invariant condition. From a technical perspective, this is simpler to maintain, and fits just fine with how almost all of our logic is setup (ie. "once action is done, do this other thing immediately")

Do you mean that `Tactic`s would/could be responsible for maintaining some time-invariant condition.

**Comment by garethellis0** [comment]
All I meant to say there was that Action's should _not_ be responsible for maintaining some time-invariant condition, not saying anything about what Tactic's should / should not do.

**Comment by amrm3lm** [comment]
do we still want `intercept_action` to not have `loop_forever` set as `false` by deafult? I ask because recently in #1619 we modified `shoot_goal_tactic` to use `intercept_action` with `loop_forever=true`
@jonathanlew

**Comment by jonathanlew** [comment]
@amrm3lm loop_forever is true but since done() is never called in that situation, it doesn't matter
