### ISSUE TITLE
Visualizer - Autoscroll Logger

### ISSUE THREAD

**Issue by qgolsteyn** [UBC-Thunderbots/Software#127]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
We would like the logger to scroll

**Describe the solution you'd like**
Scroll the logger when there are messages that go off screen.

**Comment by MathewMacDougall** [comment]
What we did with the old logger was "refresh" messages if a new one that was the same was received, rather than scrolling and printing a new message.

Eg. There would be an "age" timer next to each message, and messages would be sorted by age. If we had a message like `Robot 3 low battery` that was 3 seconds old, and received another of the same message, we would refresh the `Robot 3 low battery` message to an age of `0`.

I think this solution/behavior would help save space and make the logger more readable. Of course this would be on top of scrolling, since that's useful too. Feel free to put this in a new ticket, I just wanted to bring it up here.
