### ISSUE TITLE
Update Code Conventions to Prevent Negative Loop Exit Conditions for unsigned iterator

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1402]
### Description of the task
**Motivation:** #1403 is a good example of bugs that arise when unsigned loop iterators are used with negative loop exit conditions. 

**Context:** This problem arises from stopping warnings when comparing to `size_t` in a loop. For example, 
```
std::vector<int> A;
for (int i = 0; i < A.size(); i++)
```
throws a warning because we're comparing `i` of type `int` with the return value of `size()` which is of type `size_t`. 
One solution is to make `i` of type `size_t` to compensate, but that runs into the issues found in #1403 

**Proposed solution:** The other way to fix this bug is by casting the result of `size()` to type `int`. For example,
```
std::vector<int> A;
for (int i = 0; i < static_cast<int>(A.size()); i++)
```
This would avoid the forever loops seen in #1403

### Acceptance criteria

- [ ] Update code convevtion
- [ ] Fix all loops
- [ ] Regression tests

**Comment by jonathanlew** [comment]
@MathewMacDougall @garethellis0 @akhilveeraghanta Any feedback on proposed solution?

**Comment by garethellis0** [comment]
I'm really not sure how I feel about this. On one hand this is definitely a real problem, but on the other I really don't want to start requiring `static_cast` in `for` loops, as I feel that is both difficult to enforce and cumbersome for cases where it's not needed. 

More generally, I don't think it's reasonable to put these sort of super specific things in the coding conventions just because I think it's very unlikely that anyone will remember them or check them.

This very much feels like the exact sort of edge case that we should be covering in unit tests, but again, I totally get that it's unlikely people will always remember to. 

Sorry for the lack of concrete suggestions here, just some points I think are worth thinking about.

**Comment by jonathanlew** [comment]
> 
> 
> I'm really not sure how I feel about this. On one hand this is definitely a real problem, but on the other I really don't want to start requiring `static_cast` in `for` loops, as I feel that is both difficult to enforce and cumbersome for cases where it's not needed.
> 
> More generally, I don't think it's reasonable to put these sort of super specific things in the coding conventions just because I think it's very unlikely that anyone will remember them or check them.
> 
> This very much feels like the exact sort of edge case that we should be covering in unit tests, but again, I totally get that it's unlikely people will always remember to.
> 
> Sorry for the lack of concrete suggestions here, just some points I think are worth thinking about.

This is the sort of thing that will slip through unit tests, because people assume their loops work as intended. 

This sort of loop should be rare because we can usually use `for each` loops. 

Might be worth scrapping the warning altogether if we can't enforce a standard that prevents infinite loops.

**Comment by MathewMacDougall** [comment]
I agree something this subtle will slip through unit tests, but I think would also slip through most code review. Plus, most people aren't familiar enough with the style guide to follow this consistently (or at all) IMO.

I'm also hesitant to impose such a cumbersome convention on something so specific for similar reasons to gareth. I think it's something that will be really hard to stick to, and will be pretty much entirely on you two to enforce manually.

This is something that could maybe be caught by custom linting rules. If we gather enough valid use-cases, perhaps it's worth using / implementing a _simple_ C++ linter and integrating it into our pipeline. That way it's automated and more "well-defined". Obviously there's technical complexity and overhead with custom linting too, so just an idea.

**Comment by jonathanlew** [comment]
The convention can be simple: always write `for` loops with `int`

**Comment by garethellis0** [comment]
I haven't poked at it that much, but I imagine there is a reason that the compiler produces a warning for this behaviour (and why that would require `static_cast` to fix). I really don't think it's feasible to enforce that sort of convention. 

Overall this might be worth a call since it seems we're a tad deadlocked.

**Comment by jonathanlew** [comment]
After offline discussion, we decided against adding a convention because it would be too difficult to enforce
