### ISSUE TITLE
Unify Kick And Chip Primitives To Match Firmware

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#1579]
### Description of the task
There are currently `Chip` and `Kick` primitives in `Software` that both map to a `Shoot` primitive in `Firmware`. We should unify these so that there is a 1-to-1 mapping between software and firmware primitives.

### Acceptance criteria

- [ ] unify `kick` and `chip` primitives in `software` into a single primitive
- [ ] rename the unified software primitive and the firmware `shoot` primitive to have the same name (exact name TBD)

**Comment by jonathanlew** [comment]
I think that firmware should split shoot into chip and kick, because the parameters are semantically different in the chip and kick case. 
```
    if (chip)
    {
        app_chicker_enableAutochip(chicker, shoot_power);
    }
    else
    {
        app_chicker_enableAutokick(chicker, shoot_power);
    }
```
In this snippet we see `shoot_power` being used to represent `distance_m` in the call to `void app_chicker_enableAutochip(Chicker_t* chicker, float distance_m)`, as well as `speed_m_per_s` when calling `void app_chicker_enableAutokick(Chicker_t* chicker, float speed_m_per_s)`. 

Thoughts? @garethellis0 @MathewMacDougall @akhilveeraghanta

**Comment by garethellis0** [comment]
Totally fine with me. Consistency is the main thing I was aiming for here.

**Comment by jonathanlew** [comment]
I can reuse this [idea](https://github.com/UBC-Thunderbots/Software/issues/1415#issuecomment-659845328), so I will do https://github.com/UBC-Thunderbots/Software/issues/1577 first

**Comment by jonathanlew** [comment]
@akhilveeraghanta made a great point about kick being able to use the geneva drive and chip not being able to, so maybe we should split the shoot_primitive into kick and chip

**Comment by garethellis0** [comment]
I thought we agreed to split `shoot` into `kick` and `chip` above?

**Comment by jonathanlew** [comment]
that's right we're going to split it

**Comment by jonathanlew** [comment]
superseded by #1632
