### ISSUE TITLE
Remove `end` from firmware primitives

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#1660]
### Description of the task
The `end` function in firmware primitives is redundant because `app_primitive_manager_makeRobotSafe` accomplishes anything that the `end` function could or better. 

### Acceptance criteria

- [ ] Remove `end` from firmware primitives

**Comment by MathewMacDougall** [comment]
`makeRobotSafe` discharges the robot, which we may not always want when switching primitives?

**Comment by jonathanlew** [comment]
`app_primitive_manager_makeRobotSafe` is called every time a primitive ends and it does not discharge the robots

**Comment by MathewMacDougall** [comment]
Ah. I may have missed this whenever we had discussion about what `app_primitive_manager_makeRobotSafe` should do, but I'd assume "safe" means discharging the robots as well so that they can be handled by a human. I know I also have been vocal _against_ discharging caps between primitives, so this doesn't totally align.

IMO `makeRobotSafe` _should_ discharge the caps as well, as we should either have a slightly different function that gets called when primitives end, or _maybe_ we add a parameter to determine if we discharge or not when making the robot safe.

Eg. we could either have
`makeRobotSafe(enum Discharge)`

or

```
makeRobotSafe() {
    stopRobot();
    discharge();
}
```
and call `stopRobot()` at the end of primitives
