### ISSUE TITLE
Handle EStop state

### ISSUE THREAD

**Issue by henryymliu** [UBC-Thunderbots/Software#224]
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
The dongle class has a callback that updates the EStop state. In the old AI, it was only used to tell if the EStop was broken, but we can use this further in the new AI to warn the user when the EStop is on (for example), and/or to stop sending packets to the radio.

**Describe the solution you'd like**
Maybe publish the state from the radio node? Haven't thought much about it yet.

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by MathewMacDougall** [comment]
Publishing e-stop state from the radio node makes the most sense.

My only concern about stopping AI from sending packets is that it's risky to assume that when we press the e-stop, the robots receive an "e-stop" packet before AI stops sending packets entirely. There's no reason I can think of to minimize radio spam while the e-stop is active because we aren't actively playing a game, unless we start sending packets too fast for the dongle and back up its queues.
