### ISSUE TITLE
Implement generatePasses In PassGenerator

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#382]
### Description of the task
Fully implement the `generatePasses` function in the `PassGenerator` class.

### Outline the task in more detail
We should roughly base this function on how pass generation was done in the old code. See https://wiki.ubcthunderbots.ca/-LNDlFcpV2p--IwnWNlJ/software/passing#advice-sidenotes-random-info for details. The function currently has a very simple implementation, just generating passes with all 0 values.

We should also implement some basic logic to just remove and re-generate all the passes if the quality of the best pass is below some threshold (probably set via a dynamic parameter). This bit probably shouldn't go in the `generatePasses` class, but they're pretty coupled, hence why they're in the same issue.

### Acceptance criteria

- [ ] `generatePasses` in `PassGenerator` is implemented
- [ ] Implement functionality to remove and re-start all passes currently being optimized if the best pass so far is below a given threshold

**Comment by garethellis0** [comment]
@JamesPetrie - could you give a quick overview of the impetus behind re-generating passes? Are we trying to re-generate passes around current passes to help avoid local minima? Are we generating passes as far away as possible to make sure we're exploring the entire world as it changes? Or something else entirely?

**Comment by JamesPetrie** [comment]
A little bit of both really. The ideal case is that there are ~10 local maxima and each of them is being tracked as the world changes. Because local maxima could quickly change to global maxima, and also to give alternative pass options.

In order to explore as much of the space as possible we wanted to quassi-randomly test new starting points. Since points are being removed by the merging they have to be added back anyways. And the worst points are removed under the assumption that if they were close to a good point 10 GD iterations would be enough to make them better than the bottom 20% of passes.

The logic used in the old code actually didn't consider the location of current points when generating new ones, but this was mainly because that made it less complicated.

We initially considered uniformly sampling from the space, but chose a heuristic to give a bit more direction to the search.

To do this the field is considered in radial coordinates with the centre at the passer position. It is assumed that each enemy causes a local minima in the angle it is at, and each friendly robot causes a local maxima at its radius. So the 'best' angles are the ones directly between enemy robots (at the midpoint) and the best radiuses are the ones our robots are at.

This gives roughly 6*4 potential starting points (6 enemies = 6 angular midpoints, 6-2 potential passees gives 4 radiuses).

I think the positions were sampled without replacement from these choices, and if more were needed they were sampled uniformly from the field. I believe the guess for ball speed and delay time was just hard coded, but it may be good to add some randomness to this too.

Kind of hard to describe with words so let me know if a diagram would be useful

**Comment by garethellis0** [comment]
Awesome! That makes sense, but could I get some clarification or a diagram on what you mean by each enemy causing a local minima in the angle it is at?

**Comment by JamesPetrie** [comment]
[Pass Generation Heuristic.pdf](https://github.com/UBC-Thunderbots/Software/files/2897583/Pass.Generation.Heuristic.pdf)

What I mean by minima is that it usually isn't good to pass in the direction of an enemy, so test angles that are as far from enemies as possible. (Enemies create 'valleys' behind them in the pass quality function).

Now even from this diagram it shows that this heuristic is missing some potential areas. It might be good to add in some phantom enemies every 60 degrees or so if there aren't any enemies there so we don't completely miss areas of the field.

**Comment by garethellis0** [comment]
Ah, makes sense, thanks!

**Comment by MathewMacDougall** [comment]
Interesting heuristic, and nice image (very useful) :+1:

**Comment by JamesPetrie** [comment]
Just double checked and it looks like half of the generated points used this heuristic and the other half were sampled uniformly (using the wrong field dimensions though). And for the heuristic it looks like we tried to guess a good ball speed based on how fast to kick to avoid one of the closer enemies intercepting, and then guessed the delay time based on how long it would take our robot to get there and the given ball speed.

Now this may all have been overkill. I vaguely remember testing without the heuristic and it taking longer to converge to reasonable pass points. If the goal is to get to minimum viable product as fast as possible it may be worth leaving this function just sampling uniformly and coming back to it after the rest of the passing stuff is done.

**Comment by garethellis0** [comment]
Excellent. Thanks for the guidance on this James, that's super helpful.
