### ISSUE TITLE
Make point == operator use EPS2 to check for equality

### ISSUE THREAD

**Issue by jonathanlew** [UBC-Thunderbots/Software#678]
### Description of the task
We do a lot of (p1-p2).lensq()<EPS2. We don't want to do that everywhere. We want to be able to just use == instead.

### Outline the task in more detail
This caused bugs in the past. This will avoid future bugs

### Acceptance criteria

- [ ] Make point == operator use EPS2 to check for equality
- [ ] Refactor all code to use ==
- [ ] Testing

**Comment by MathewMacDougall** [comment]
Where do we do these kind of comparisons? The current `==` operator for the `Point` class already uses an EPS value as suggested. Are the bugs from the past reproducible? We would probably want to consider making the EPS value slightly larger in that case, since right now it's the absolute smallest it can reasonably be.

**Comment by jonathanlew** [comment]
Mostly in geom/util.cpp. Maybe the task is to evaluate switching them all to ==

**Comment by MathewMacDougall** [comment]
Ah I see what you mean. That makes more sense to me then.

What bugs did this cause in the past?

**Comment by garethellis0** [comment]
@jsn0716 @scveloso - please make sure to account for this in the geom re-write, feel free to close if no longer relevant.

**Comment by jonathanlew** [comment]
I think that new geom has addressed this with FIXED_EPSILON, unit testing, etc. so we can close it.
