### ISSUE TITLE
Restructure Firmware 

### ISSUE THREAD

**Issue by MathewMacDougall** [UBC-Thunderbots/Software#790]
### Description of the task

We want to refactor and cleanup the firmware for both the robots and dongle. This is difficult since there are no tests, so integration tests are our only option to make sure things work.

We should figure out what areas / modules we want to refactor and in what order, and figure out how we will test along the way to make sure we don't break anything.

### Acceptance criteria

- [ ] Make a plan for firmware refactoring and testing

**Comment by garethellis0** [comment]
After offline discussion, high level plan is as follows:

### Robot
* Refactor the current firmware codebase for the robot so there is a clear API between the high level logic and low level hardware interfaces (ie. kick, turn wheel 3 at 15 rpm, etc.)
* Tests 
  * Kick the ball at a set speed
  * Chip a set distance
  * Move to a series of points

### Dongle:
* This is really just about cleanup, since this code doesn't need to be portable
* Tests:
  * Send a primitive to the robot, and have the robot send back a specific status message in reply (thus checking round-trip functionality)
